### ISSUE TITLE
請問我可以用程式碼來控制連線嗎?

### ISSUE THREAD

**Issue by HuJK** [zhouer/ZTerm#2]
想用java寫自動推文機器人，找到了這個程式。請問有API可以直接用程式碼登入嗎?還是要改原始碼?

**Comment by zhouer** [comment]
沒有 API 可以用喔，如果你只是要自動登入和推文其實連 VT100 跟 telnet protocol 都不需要處理，
直接用 Expect http://expect.sourceforge.net/ 就可以做到絕大多數的功能了。

**Comment by HuJK** [comment]
真的嗎?不過我還想要做到讀取文章資訊等功能!

請問一下，作者大大您把螢幕要顯示的資訊儲存在哪裡?
因為我想要讀取文章資訊，又不想處理(其實是不會處裡)vt100的指令，所以想要找個現成的vt100解析器。您的程式就是一個很棒的解析器!先解析，輸出到螢幕上(我設定隱藏視窗)。我直接讀取處理過的資訊就好。

我目前是想要直接讀取顯示在螢幕上的字元陣列，串成字串。我是打算直接改成public，直接讀取。

但是我才剛學java(不到半年)，有好多看不太懂的程式碼，找不到儲存顯示資訊地點!可以直接告訴我嗎?(我目前是想朝copy這個function下手)

還有，處裡按鈕事件的function的位置也拜託了(要模擬按鍵用)!

//////////////////////////////////////////////////
我已經改寫getSelectedText()，弄了個
getText()了，關於按鈕事件function還望指點!

**Comment by zhouer** [comment]
我覺得你應該拿 https://github.com/zhouer/ZTerm/blob/master/org/zhouer/protocol/Telnet.java
去用就可以了，VT100 控制碼全部都略過就好。
https://github.com/zhouer/ZTerm/blob/master/org/zhouer/protocol/Standalone.java 是 standalone 的 telnet/ssh client，不包含 VT100 你可以從這裡切入。
直接讀 VT100 parse 後的東西很辛苦，我建議你可以不要這麼做。

**Comment by HuJK** [comment]
getSelectedText()被我改寫成了:
```java
    public String getText(){
        int i, j, k;
        StringBuffer sb = new StringBuffer();
        for( i = 0; i < totalrow; i++ ) {
            j=0;
            if( j == totalcol ) {
                continue;
            }
            for( j = totalcol - 1; j >= 0; j-- ) {
                if( mbc[i][j] != 0 ) {
                    break;
                }
            }
            for( k = 0; k <= j; k++ ) {
                    if( mbc[i][k] == 0 ) {
                        sb.append( " " );
                    } else if( mbc[i][k] == 1 ) {
                        sb.append( text[i][k] );
                    }
                } 
            if(sb.charAt(sb.length() -1) != '\n'){
                sb.append( "\n" );
            }
        }
        return sb.toString();
    }
```
用途是取的現在式窗上的所有文字(類似全選+複製得到的東西)

那要怎麼把鍵盤取得的東西丟進Telnet的Write函數呢?我猜應該不是getKeyCode()

**Comment by HuJK** [comment]
您好，現在已經成功使用pasteText()函數將字元送入ptt。

請問如何將方向鍵、Home/End鍵送入呢?

**Comment by zhouer** [comment]
https://github.com/zhouer/ZTerm/blob/master/org/zhouer/vt/User.java#L30
https://github.com/zhouer/ZTerm/blob/master/org/zhouer/vt/User.java#L143
https://github.com/zhouer/ZTerm/blob/master/org/zhouer/zterm/Session.java#L182

**Comment by HuJK** [comment]
十分感謝!搞定了，但是忘記回。
